### ISSUE TITLE
Sceptre error message does not contain file info

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#1048]
### Subject of the issue
Sceptre error message does not provide info on the file containing the error. 

### Your environment
* sceptre ver 2.5.0
* python 3.7.10
* Mac OSX 10.14.6

### Steps to reproduce
create an sceptre template that contains an error

config/dev/noop.yaml:
```
template_path: noop.yaml
stack_name: noop
sceptre_user_data:
  Test: !Sub 'error'
```

templates/noop.yaml
```
Description: noop template
AWSTemplateFormatVersion: 2010-09-09
Resources:
  touchNothing:
    Type: AWS::CloudFormation::WaitConditionHandle
``` 

run `sceptre generate dev`

### Expected behaviour
I expect the error message to show which file contains the error. 

### Actual behaviour
Instead I see something like this in the error message.. `in "<unicode string>", line 36, column 20:`

<details>
<summary>error log</summary>

    ➜  sceptre generate dev
    Traceback (most recent call last):
      File "/Users/zaro0508/work-github/sceptre/sceptre/config/reader.py", line 410, in _render
        config = yaml.safe_load(rendered_template)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
        return load(stream, SafeLoader)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
        return loader.get_single_data()
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
        return self.construct_document(node)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 60, in construct_document
        for dummy in generator:
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
        value = self.construct_mapping(node)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 218, in construct_mapping
        return super().construct_mapping(node, deep=deep)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 143, in construct_mapping
        value = self.construct_object(value_node, deep=deep)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
        data = constructor(self, node)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/yaml/constructor.py", line 429, in construct_undefined
        node.start_mark)
    yaml.constructor.ConstructorError: could not determine a constructor for the tag '!Sub'
      in "<unicode string>", line 4, column 9:
          Test: !Sub 'error'
                ^
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/var/pyenv/versions/py37-sceptredev/bin/sceptre", line 33, in <module>
        sys.exit(load_entry_point('sceptre', 'console_scripts', 'sceptre')())
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/var/pyenv/versions/3.7.10/envs/py37-sceptredev/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/Users/zaro0508/work-github/sceptre/sceptre/cli/helpers.py", line 37, in decorated
        return func(*args, **kwargs)
      File "/Users/zaro0508/work-github/sceptre/sceptre/cli/template.py", line 64, in generate_command
        plan = SceptrePlan(context)
      File "/Users/zaro0508/work-github/sceptre/sceptre/plan/plan.py", line 34, in __init__
        all_stacks, command_stacks = config_reader.construct_stacks()
      File "/Users/zaro0508/work-github/sceptre/sceptre/config/reader.py", line 227, in construct_stacks
        stack = self._construct_stack(rel_path, stack_group_config)
      File "/Users/zaro0508/work-github/sceptre/sceptre/config/reader.py", line 501, in _construct_stack
        config = self.read(rel_path, stack_group_config)
      File "/Users/zaro0508/work-github/sceptre/sceptre/config/reader.py", line 321, in read
        this_config = self._recursive_read(directory_path, filename, config)
      File "/Users/zaro0508/work-github/sceptre/sceptre/config/reader.py", line 362, in _recursive_read
        child_config = self._render(directory_path, filename, stack_group_config) or {}
      File "/Users/zaro0508/work-github/sceptre/sceptre/config/reader.py", line 413, in _render
        "Error parsing {}:\n{}".format(abs_directory_path, err)
    ValueError: Error parsing /Users/zaro0508/work-sage/organizations-infra/sceptre/scipool/config/develop:
    could not determine a constructor for the tag '!Sub'
      in "<unicode string>", line 4, column 9:
          Test: !Sub 'error'
                ^

</details>

**Comment by jfalkenstein** [comment]
This was actually resolved recently with the error handling fix we caused. Using the --debug flag raises the error in completion.
