### ISSUE TITLE
Requirement already satisfied issue with Sceptre installation

### ISSUE THREAD

**Issue by ercindemir** [Sceptre/sceptre#1067]
I'm using sceptre in a docker image without an issue and want to do some tests in my local machine as well. But I can't install it

Following up [this documentation](https://sceptre.cloudreach.com/2.5.0/docs/install.html).

I'm trying to install sceptre with the command `pip install sceptre`. But I get the output below.

```
Requirement already satisfied: sceptre in /usr/local/lib/python3.9/site-packages (2.5.0)
Requirement already satisfied: Jinja2<3,>=2.8 in /usr/local/lib/python3.9/site-packages (from sceptre) (2.11.3)
Requirement already satisfied: PyYaml<6.0,>=5.1 in /usr/local/lib/python3.9/site-packages (from sceptre) (5.4.1)
Requirement already satisfied: networkx<3,>=2.4 in /usr/local/lib/python3.9/site-packages (from sceptre) (2.5.1)
Requirement already satisfied: click<8.0,>=7.0 in /usr/local/lib/python3.9/site-packages (from sceptre) (7.1.2)
Requirement already satisfied: boto3<2.0,>=1.3 in /usr/local/lib/python3.9/site-packages (from sceptre) (1.17.67)
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python3.9/site-packages (from sceptre) (0.4.4)
Requirement already satisfied: six<2.0.0,>=1.11.0 in /usr/local/lib/python3.9/site-packages (from sceptre) (1.16.0)
Requirement already satisfied: packaging<17.0,>=16.8 in /usr/local/lib/python3.9/site-packages (from sceptre) (16.8)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.9/site-packages (from boto3<2.0,>=1.3->sceptre) (0.10.0)
Requirement already satisfied: botocore<1.21.0,>=1.20.67 in /usr/local/lib/python3.9/site-packages (from boto3<2.0,>=1.3->sceptre) (1.20.67)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /usr/local/lib/python3.9/site-packages (from boto3<2.0,>=1.3->sceptre) (0.4.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.9/site-packages (from botocore<1.21.0,>=1.20.67->boto3<2.0,>=1.3->sceptre) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python3.9/site-packages (from botocore<1.21.0,>=1.20.67->boto3<2.0,>=1.3->sceptre) (1.26.4)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.9/site-packages (from Jinja2<3,>=2.8->sceptre) (2.0.1)
Requirement already satisfied: decorator<5,>=4.3 in /usr/local/lib/python3.9/site-packages (from networkx<3,>=2.4->sceptre) (4.4.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.9/site-packages (from packaging<17.0,>=16.8->sceptre) (2.4.7)
```

Tried this

```
pip uninstall sceptre
pip install sceptre
```

I read some questions on stackoverflow. People usually resolve this issue with reinstalling the package. In my case, it didn't work. When I run pip list, I can see the version. But I can't run sceptre --version command. I tried installing sceptre on different machines but no luck. Is something wrong with sceptre? That would be great if the documentation makes a bit clear at local installation.

Thanks!

**Comment by ngfgrant** [comment]
Hey @ercindemir - out of interest are you using virtualenvironments?

**Comment by mhmtsvr** [comment]
Hey @ngfgrant  I'm simply trying to install it on mac. On [the documentation](https://sceptre.cloudreach.com/2.5.0/docs/install.html), it says `We highly recommend using Sceptre from within a virtualenv`, but can't I install it on mac?

**Comment by ercindemir** [comment]
Hey @ngfgrant I'm simply trying to install it on mac. On [the documentation](https://sceptre.cloudreach.com/2.5.0/docs/install.html), it says `We highly recommend using Sceptre from within a virtualenv`, but can't I install it on mac?

**Comment by craighurley** [comment]
Hi @ercindemir, @ngfgrant was referring to python virtual environment: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

**Comment by zaro0508** [comment]
@ercindemir  please try install in a virtualenv.  re-open this issue if it doesn't work for you.

**Comment by ercindemir** [comment]
@zaro0508 I still get the same output even in a virtualenv.

```
Requirement already satisfied: sceptre in ./env/lib/python3.9/site-packages (2.5.0)
Requirement already satisfied: boto3<2.0,>=1.3 in ./env/lib/python3.9/site-packages (from sceptre) (1.18.0)
Requirement already satisfied: colorama>=0.3.9 in ./env/lib/python3.9/site-packages (from sceptre) (0.4.4)
Requirement already satisfied: click<8.0,>=7.0 in ./env/lib/python3.9/site-packages (from sceptre) (7.1.2)
Requirement already satisfied: six<2.0.0,>=1.11.0 in ./env/lib/python3.9/site-packages (from sceptre) (1.16.0)
Requirement already satisfied: Jinja2<3,>=2.8 in ./env/lib/python3.9/site-packages (from sceptre) (2.11.3)
Requirement already satisfied: packaging<17.0,>=16.8 in ./env/lib/python3.9/site-packages (from sceptre) (16.8)
Requirement already satisfied: networkx<3,>=2.4 in ./env/lib/python3.9/site-packages (from sceptre) (2.5.1)
Requirement already satisfied: PyYaml<6.0,>=5.1 in ./env/lib/python3.9/site-packages (from sceptre) (5.4.1)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in ./env/lib/python3.9/site-packages (from boto3<2.0,>=1.3->sceptre) (0.5.0)
Requirement already satisfied: botocore<1.22.0,>=1.21.0 in ./env/lib/python3.9/site-packages (from boto3<2.0,>=1.3->sceptre) (1.21.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./env/lib/python3.9/site-packages (from boto3<2.0,>=1.3->sceptre) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./env/lib/python3.9/site-packages (from botocore<1.22.0,>=1.21.0->boto3<2.0,>=1.3->sceptre) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in ./env/lib/python3.9/site-packages (from botocore<1.22.0,>=1.21.0->boto3<2.0,>=1.3->sceptre) (1.26.6)
Requirement already satisfied: MarkupSafe>=0.23 in ./env/lib/python3.9/site-packages (from Jinja2<3,>=2.8->sceptre) (2.0.1)
Requirement already satisfied: decorator<5,>=4.3 in ./env/lib/python3.9/site-packages (from networkx<3,>=2.4->sceptre) (4.4.2)
Requirement already satisfied: pyparsing in ./env/lib/python3.9/site-packages (from packaging<17.0,>=16.8->sceptre) (2.4.7)
WARNING: You are using pip version 21.0.1; however, version 21.1.3 is available.
You should consider upgrading via the '/User/x/env/bin/python3.9 -m pip install --upgrade pip' command.
```

**Comment by craighurley** [comment]
@ercindemir a few of things:

1. That output indicates you are not using a virtual env.  The paths should look something like `/PATH/TO/.pyenv/versions/PYTHON_VERSION/envs/ENV_NAME`.  Please read the link I provided earlier and get that working first.
2. Please provide more detail (the commands you used to create and activate the virtual env, the `pip install` command, the output of the sceptre commands you are using and that are failing, the `sceptre --version` command output).
3. Finally, I don't see anything wrong with the provided output; all it's saying is you are trying to install something that is already installed.

**Comment by ercindemir** [comment]
thank you @craighurley 

I reviewed everything. Sceptre installed but it does not work as expected. I try to generate one template that works fine in a docker container, but it does not work in the virtual environment I just created.

The error I get
$ sceptre generate infra/slack/channels.yaml
```

Traceback (most recent call last):
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/config/reader.py", line 395, in _render
    config = yaml.safe_load(rendered_template)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!sceptre_s3_upload'
  in "<unicode string>", line 4, column 7:
        - !sceptre_s3_upload functions/eks ...
          ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxx/env/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/Users/xxxxx/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxxxx/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/cli/helpers.py", line 37, in decorated
    return func(*args, **kwargs)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/cli/template.py", line 64, in generate_command
    plan = SceptrePlan(context)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/plan/plan.py", line 34, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/config/reader.py", line 228, in construct_stacks
    stack = self._construct_stack(rel_path, stack_group_config)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/config/reader.py", line 489, in _construct_stack
    config = self.read(rel_path, stack_group_config)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/config/reader.py", line 306, in read
    this_config = self._recursive_read(directory_path, filename, config)
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/config/reader.py", line 347, in _recursive_read
    child_config = self._render(directory_path, filename, stack_group_config) or {}
  File "/Users/xxxxx/env/lib/python3.9/site-packages/sceptre/config/reader.py", line 397, in _render
    raise ValueError(
ValueError: Error parsing /Users/xxxxx/gitlab/iac-aws/config/europe/serverless:
could not determine a constructor for the tag '!sceptre_s3_upload'
  in "<unicode string>", line 4, column 7:
        - !sceptre_s3_upload functions/eks ...
          ^

```

Here is how I installed the virtual environment from the link you provided

```
python3 -m pip install --user --upgrade pip
python3 -m pip --version
python3 -m pip install --user virtualenv
python3 -m venv env
source env/bin/activate

```
I also confirmed of the localtion of Python interpreter
which python

.../env/bin/python   (as it is supposed to be)


What am I missing? I can't figure where I can run with no issue but can't in a virtual environment.

**Comment by craighurley** [comment]
Do you want to provide the sceptre config and cfn template as examples too?

**Comment by ercindemir** [comment]
Thanks @craighurley ! sceptre_s3_upload changed my output now.

I'm getting unclear output like this.
```
A    W    S    T    e    m    p    l    a    t    e    F    o    r    m    a    t    V    e    r    s    i    o    n    :         '    2    0    1    0    -    0    9    -    0    9    '
    D    e    s    c    r    i    p    t    i    o    n    :         "    C    r    e    a    t    e         S    l    a    c    k         N    o    t    i    f    i    c    a    t    i    o    n         C    h    a    n    n    e    l    s    "
    P    a    r    a    m    e    t    e    r    s    :
              S    l    a    c    k    W    o    r    k    s    p    a    c    e    I    d    :
                        T    y    p    e    :         S    t    r    i    n    g
                        D    e    f    a    u    l    t    :         T    0    3    J    1    G    Y    9    T         #    T    h    i    s         i    s         t    h    e         F    l    y    b    i    t    s         W    o    r    k    s    p    a    c    e    I    d         -         I    n         t    h    e    o    r    y         i    t         s    h    o    u    l    d         n    e    v    e    r         b    e         c    h    a    n    g    e    d
              S    l    a    c    k    C    h    a    n    n    e    l    I    d    :
                        T    y    p    e    :         S    t    r    i    n    g
                        D    e    f    a    u    l    t    :         G    R    F    G    B    L    1    A    7         #    T    h    i    s         i    s         f    o    r         t    h    e         #    a    l    e    r    t    s         c    h    a    n    n    e    l
              S    l    a    c    k    D    e    v    C    h    a    n    n    e    l    I    d    :
                        T    y    p    e    :         S    t    r    i    n    g
                        D    e    f    a    u    l    t    :         C    0    1    5    F    U    M    6    1    K    N         #    T    h    i    s         i    s         f    o    r         t    h    e         #    a    l    e    r    t    s    -    d    e    v         c    h    a    n    n    e    l
              S    l    a    c    k    A    n    a    l    y    t    i    c    s    A    l    e    r    t    s    C    h    a    n    n    e    l    I    d    :
                        T    y    p    e    :         S    t    r    i    n    g
                        D    e    f    a    u    l    t    :         "    C    0    2    4    J    G    H    E    R    5    5    "         #    T    h    i    s         i    s         f    o    r         t    h    e         #    a    n    a    l    y    t    i    c    s    -    a    l    e    r    t    s         c    h    a    n    n    e    l
              S    l    a    c    k    A    n    a    l    y    t    i    c    s    E    x    p    o    r    t    A    l    e    r    t    s    C    h    a    n    n    e    l    I    d    :
                        T    y    p    e    :         S    t    r    i    n    g
                        D    e    f    a    u    l    t    :         "    G    0    1    D    R    H    J    K    M    C    6    "         #    T    h    i    s         i    s         f    o    r         t    h    e         #    a    n    a    l    y    t    i    c    s    -    e    x    p    o    r    t    -    p    r    o    j    e    c    t         c    h    a    n    n    e    l
              S    n    s    T    o    p    i    c    s    T    o    R    e    g    i    s    t    e    r    T    o    :
                        T    y    p    e    :         C    o    m    m    a    D    e    l    i    m    i    t    e    d    L    i    s    t
                        D    e    s    c    r    i    p    t    i    o    n    :         T    h    e         l    i    s    t         o    f         S    N    S         T    o    p    i    c    s         t    o         r    e    g    i    s    t    e    r         t    o         t    h    e         a    l    e    r    t    s         s    l    a    c    k         c    h   
``` 

I can't provide my CF template here but I can reassure you that it works perfectly fine in a docker image. I believe the problem is my configuration not template. 

Docker image requirements:
pyyaml==5.4
troposphere==3.0.2
sceptre==2.6.2
awscli

Docker file:
FROM python:3.8-alpine
WORKDIR /usr/src/app

RUN apk add git jq docker bash

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip3 install --no-deps awscli boto3
RUN pip install sceptre-s3-packager
RUN pip install git+https://github.com/rancher/client-python.git@master

I also run these commands, but no luck.
