### ISSUE TITLE
Docker Sceptre throws "ModuleNotFoundError: No module named 'resolver.rcmd'"

### ISSUE THREAD

**Issue by jordie23** [Sceptre/sceptre#1072]
### Subject of the issue

Our CI build, which is using sceptre in docker and isn't fixed to a specific version, started exiting with this error after the release of 2.6.1. 

### Your environment
* version of sceptre: 2.6.1 (Note: 2.6.0 appears to work.)
* version of python: 3.7 I think? Whatever is in the offical docker `cloudreach/sceptre:latest`
* docker

### Steps to reproduce

Call the latest container however you want.

We're using docker-compose but the following one-liner will also see the same error

e.g. 

```
docker run -v $(pwd):/project cloudreach/sceptre:2.6.1 launch -y any/config/path
```

### Expected behaviour

It should run sceptre without errors.

### Actual behaviour

Throws this error:

```
Traceback (most recent call last):
--
  | File "/usr/local/bin/sceptre", line 33, in <module>
  | sys.exit(load_entry_point('sceptre==2.6.1', 'console_scripts', 'sceptre')())
  | File "/usr/local/lib/python3.7/site-packages/click-8.0.1-py3.7.egg/click/core.py", line 1137, in __call__
  | return self.main(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/click-8.0.1-py3.7.egg/click/core.py", line 1062, in main
  | rv = self.invoke(ctx)
  | File "/usr/local/lib/python3.7/site-packages/click-8.0.1-py3.7.egg/click/core.py", line 1668, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/usr/local/lib/python3.7/site-packages/click-8.0.1-py3.7.egg/click/core.py", line 1404, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/usr/local/lib/python3.7/site-packages/click-8.0.1-py3.7.egg/click/core.py", line 763, in invoke
  | return __callback(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/click-8.0.1-py3.7.egg/click/decorators.py", line 26, in new_func
  | return f(get_current_context(), *args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/sceptre-2.6.1-py3.7.egg/sceptre/cli/helpers.py", line 37, in decorated
  | return func(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/sceptre-2.6.1-py3.7.egg/sceptre/cli/launch.py", line 35, in launch_command
  | plan = SceptrePlan(context)
  | File "/usr/local/lib/python3.7/site-packages/sceptre-2.6.1-py3.7.egg/sceptre/plan/plan.py", line 33, in __init__
  | config_reader = ConfigReader(context)
  | File "/usr/local/lib/python3.7/site-packages/sceptre-2.6.1-py3.7.egg/sceptre/config/reader.py", line 128, in __init__
  | self._add_yaml_constructors(["sceptre.hooks", "sceptre.resolvers"])
  | File "/usr/local/lib/python3.7/site-packages/sceptre-2.6.1-py3.7.egg/sceptre/config/reader.py", line 171, in _add_yaml_constructors
  | node_class = entry_point.load()
  | File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
  | return self.resolve()
  | File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
  | module = __import__(self.module_name, fromlist=['__name__'], level=0)
  | ModuleNotFoundError: No module named 'resolver.rcmd'
```

**Comment by zaro0508** [comment]
I believe this error is due to `sceptre-cmd-resolver` not being installed to the docker container.  Sceptre ver 2.6.1 introduced the `sceptre-cmd-resolver` as a core resolver however it looks like the `setup.py` command to install sceptre in the dockerfile does not seem to install that dependency. https://github.com/Sceptre/sceptre/blob/master/Dockerfile#L6
