### ISSUE TITLE
Error with StackOutput resolver when validating stacks at the project config

### ISSUE THREAD

**Issue by wzedi** [Sceptre/sceptre#1190]
### Error with StackOutput resolver when validating stacks at the project config level

A similar issue, at least by the description, has been logged and resolved before: https://github.com/Sceptre/sceptre/issues/483.

But in this case it is `validate` that fails and it fails when running against config root but not when running specific environments.

Consider the following environment:

```
├── config
│   ├── dev
│   │   ├── ecs
│   │    │   ├── ecs.yaml
│   │    │   ├── ecs-cluster.yaml
│   │    │   └── config.yaml
│   │   ├── redis
│   │    │   ├── redis.yaml
│   │    │   └── config.yaml
│   │   └── config.yaml
│   ├── staging
│   │   ├── ecs
│   │    │   ├── ecs.yaml
│   │    │   ├── ecs-cluster.yaml
│   │    │   └── config.yaml
│   │   ├── redis
│   │    │   ├── redis.yaml
│   │    │   └── config.yaml
│   │   └── config.yaml
│   ├── prod
│   │   ├── ecs
│   │    │   ├── ecs.yaml
│   │    │   ├── ecs-cluster.yaml
│   │    │   └── config.yaml
│   │   ├── redis
│   │    │   ├── redis.yaml
│   │    │   └── config.yaml
│   │   └── config.yaml
└── templates
    ├── ecs.yaml
    ├── ecs-cluster.yaml
    └── redis.yaml
```

We set `profile: ` in each environment as each is deployed to a different account.

Running `sceptre validate dev` works - no error.

Running `sceptre validate .` produces an error: `AttributeError: 'str' object has no attribute 'name'`

### Your environment
* Sceptre version 2.7.0 and 2.7.1
* Python version 3.7.12
* Amazon Linux 2

### Steps to reproduce

```
[2022-01-07 00:17:28] - Resolving Stack output: dev/redis/redis.yaml::RedisUserSecurityGroup
--
  | Traceback (most recent call last):
  | File "/usr/local/bin/sceptre", line 8, in <module>
  | sys.exit(cli())
  | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
  | return self.main(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
  | rv = self.invoke(ctx)
  | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
  | return __callback(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
  | return f(get_current_context(), *args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/cli/helpers.py", line 42, in decorated
  | return func(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/cli/template.py", line 38, in validate_command
  | responses = plan.validate()
  | File "/usr/local/lib/python3.7/site-packages/sceptre/plan/plan.py", line 329, in validate
  | self.resolve(command=self.validate.__name__)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/plan/plan.py", line 78, in resolve
  | self.launch_order = self._generate_launch_order(reverse)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/plan/plan.py", line 49, in _generate_launch_order
  | graph = self.graph.filtered(self.command_stacks, reverse)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/config/graph.py", line 44, in filtered
  | relevant \|= nx.algorithms.dag.ancestors(graph, stack)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/stack.py", line 234, in __eq__
  | self.sceptre_user_data == stack.sceptre_user_data and
  | File "/usr/local/lib/python3.7/site-packages/sceptre/stack.py", line 274, in sceptre_user_data
  | self._resolve_sceptre_user_data()
  | File "/usr/local/lib/python3.7/site-packages/sceptre/stack.py", line 305, in _resolve_sceptre_user_data
  | data = self._sceptre_user_data
  | File "/usr/local/lib/python3.7/site-packages/sceptre/resolvers/__init__.py", line 88, in __get__
  | resolve, getattr(instance, self.name), Resolver
  | File "/usr/local/lib/python3.7/site-packages/sceptre/helpers.py", line 63, in _call_func_on_values
  | func_on_instance(key)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/helpers.py", line 59, in func_on_instance
  | _call_func_on_values(func, value, cls)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/helpers.py", line 66, in _call_func_on_values
  | func_on_instance(index)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/helpers.py", line 57, in func_on_instance
  | func(attr, key, value)
  | File "/usr/local/lib/python3.7/site-packages/sceptre/resolvers/__init__.py", line 81, in resolve
  | attr[key] = value.resolve()
  | File "/usr/local/lib/python3.7/site-packages/sceptre/resolvers/stack_output.py", line 128, in resolve
  | stack for stack in self.stack.dependencies if stack.name == friendly_stack_name
  | File "/usr/local/lib/python3.7/site-packages/sceptre/resolvers/stack_output.py", line 128, in <genexpr>
  | stack for stack in self.stack.dependencies if stack.name == friendly_stack_name
  | AttributeError: 'str' object has no attribute 'name'
```

### Expected behaviour
The validate command should work from the config root path as well as from the environment paths.

### Actual behaviour
Running validate with an environment path works. Running `validate .` produces the error.

**Comment by wzedi** [comment]
And after having done a little more reading around the issues I found this: https://github.com/Sceptre/sceptre/issues/1000#issuecomment-986447461

**Comment by jfalkenstein** [comment]
@wzedi , if I'm not mistaken, I believe this issue stems from inheriting dependencies. Do you happen to be using the `!stack_output` resolver in a StackGroup config (rather than a Stack Config)? Also, are you explicitly setting "dependencies" anywhere on a Stack or StackGroup Config?

There are a couple bugs in the way dependencies and Resolvers are layered on top of each other. In preparation for the next version of Sceptre, I've been overhauling the whole resolver system and I addressed some of these bugs that I found. 

Would it be possible for you to pull the version of Sceptre off the current master branch and install that to see if that solves it for you? We're nearing another release (some time in February) which will bring a pretty significant overhaul and improvement to all the Resolver issues.

**Comment by avatarworf** [comment]
@jfalkenstein Experiencing the same issue, using v3.0.0
Things I've checked:
 * no `!stack_output` in the Stack group configuration files
 * removed `dependencies:` configuration in sceptre stack configuration files, where already duplicated by `!stack_output`
 * even removed other `dependencies:` from the sceptre stack config in order to rule out this as a cause

I am migrating from a sceptre v1 deployment `sceptre --var-file=variables.yaml launch-env .` to `sceptre --var-file=variables.yaml launch -y .` but am receiving the same behaviour

Am curious about the changes from sceptre v1 to v3 when it comes to the directory structure under `config/` as I think this has an impact

To Reference the [documentation](https://github.com/Sceptre/sceptre/blame/master/docs/_source/docs/architecture.rst#L85-L96) this would allow  `sceptre --var-file=variables.yaml launch -y prod` to be successfully executed.  But if the directory structure from v1 was as follows

.. code-block:: yaml
      - config
          - network
                - vpc.yaml
                - subnet.yaml
            - frontend
                - api-gateway.yaml
            - application
                - lambda-get-item.yaml
                - lambda-put-item.yaml
            - database
                - dynamodb.yaml

then calling of `sceptre --var-file=variables.yaml launch -y .` should produce the same results, but yet various errors creep up, like the `AttributeError: 'str' object has no attribute 'name'` or `networkx.exception.NetworkXError: The node database/dynamodb is not in the graph.` As to which error appears seems to be random depending on how sceptre has built the dependency tree using networkx

Currently I see the work around is to execute each part independently. This does look to function as a possible step solution in the migration from v1 to v3, but I don't think this is the overall goal of the sceptre project

```bash
sceptre --var-file=variables.yaml launch -y network
sceptre --var-file=variables.yaml launch -y database
sceptre --var-file=variables.yaml launch -y application
sceptre --var-file=variables.yaml launch -y frontend
```

**Comment by zaro0508** [comment]
it always works when I follow @jfalkenstein's suggestions.

**Comment by avatarworf** [comment]
@jfalkenstein @zaro0508 Thanks for the feedback, I think this is what was causing my confusion i had in #1215 

Problem with Option 1) would be that I need to change the !stack_output paths, too append the new path.

Problem with Option 2) as I've seen with experimenting with #1215, If I found the 'last stack' without dependencies (aka sceptre launch frontend) then I'd need to be sure each stack has some sort of cascade to dependancies so that all stacks are launch.  So that probably the first stack launched probably would be the VPC and build everything up from that point.

Thanks for the insight, I'll have to have a review of the most appropriate option to go with.

**Comment by jfalkenstein** [comment]
There hasn't been any activity on this issue for quite a while and there doesn't appear to be an explicit feature request or bug identified. I'm going to go ahead and close this. If there is a specific feature request or bug, a new, more targeted issue should be opened requesting that.
