### ISSUE TITLE
Sceptre fails when multiple resolvers return None

### ISSUE THREAD

**Issue by ykhalyavin** [Sceptre/sceptre#1223]
### Sceptre fails when multiple resolvers return None
When multiple resolvers in a stack config return None sceptre fails.

### Your environment
* version of sceptre (3.1.0)
* version of python (3.8.10)
* which OS/distro -- windows 10, linux

### Steps to reproduce
```
sceptre_user_data:
  some_structure:
    abc0: !resolver1
    abc1: !resolver2
    abc3: !resolver3
```

### Expected behaviour
Variables in the stack should get None (the actual values that the resolvers returned)

### Actual behaviour
sceptre fails with
```
Traceback (most recent call last):

  File "scripts/render-templates.py", line 73, in main

    for stack, template_body in plan.generate().items():

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\plan\plan.py", line 351, in generate

    return self._execute(*args)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\plan\plan.py", line 43, in _execute

    return executor.execute(*args)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\plan\executor.py", line 55, in execute

    stack, status = future.result()

  File "C:\Users\ykhalyavin\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 432, in result

    return self.__get_result()

  File "C:\Users\ykhalyavin\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result

    raise self._exception

  File "C:\Users\ykhalyavin\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\plan\executor.py", line 62, in _execute

    result = getattr(actions, self.command)(*args)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\hooks\__init__.py", line 104, in decorated

    response = func(self, *args, **kwargs)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\plan\actions.py", line 634, in generate

    return self.stack.template.body

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\stack.py", line 352, in template

    sceptre_user_data=self.sceptre_user_data,

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\resolvers\__init__.py", line 191, in __get__

    container = super().__get__(stack, stack_class)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\resolvers\__init__.py", line 93, in __get__

    return self.get_resolved_value(stack, stack_class)

  File "C:\Users\ykhalyavin\venv\cfn\lib\site-packages\sceptre\resolvers\__init__.py", line 245, in get_resolved_value

    del attr[key]

IndexError: list assignment index out of rangeTraceback (most recent call last):
```

**Comment by ykhalyavin** [comment]
@jfalkenstein this is a slightly different use case related to a big with deletion of indexes from a list. The fix is here https://github.com/Sceptre/sceptre/compare/master...ykhalyavin:fix_resolvers_returning_none_1223. Will get back once test it in a couple of days

**Comment by jfalkenstein** [comment]
Ah! I think I'm understanding what you're saying now. In a list with three resolvers returning None, If we try to delete indexes 0, 1, and 2 from that list, the indexes of the items will fail after each deletion. Interesting! I wasn't catching the gist. 

With that said, I looked at your fix and I don't think that's any more correct. Remember, that code "works" right now for both dict keys and list indexes. You need to account for the fact that the "key" might be a dict key or a list index. `keys_to_delete` might even have a combination of the both. I think a better approach to address this would probably be something like this: 

```python
list_items_to_delete = []
for attr, key in keys_to_delete:
        if isinstance(attr, list):
            # If it's a list, we want to gather up the items to remove from the list. We don't want to modify the list length yet.
            # Since removals will change all the other list indexes, we don't wan't to modify lists yet. 
            list_items_to_delete.append(attr, attr[key])
        else:    
            del attr[key]

for containing_list, item in list_items_to_delete:
    containing_list.remove(item)
```

Doing something like this allows us to remove the specific items from the list by _value_ rather than by index.

**Comment by ykhalyavin** [comment]
@jfalkenstein added your code almost unchanged and as per unit tests, when we have multilevel keys, the keys can be empty (have a look at **expected b/c** keys below). In my understanding we need to remove any key that contains no data, e.g. a: [{}]/[]/{}, etc ?

`        self.mock_object.resolvable_container_property = {
            'a': 4,
            'b': [
                resolver,
            ],
            'c': [{
                'v': resolver
            }],
            'd': 3
        }
        expected = {'a': 4, 'b': [], 'c': [{}], 'd': 3}
        assert self.mock_object.resolvable_container_property == expected`

**Comment by jfalkenstein** [comment]
I'm not sure on your question. Why don't you put up a Pull request and we can discuss your specific code changes there?
