### ISSUE TITLE
An empty var file causes Sceptre to blow up

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1234]
### Subject of the issue
If an empty var file is passed to Sceptre, Sceptre raises an exception

### Your environment
* version of sceptre (sceptre --version) 3.0.0
* version of python (python --version) 3.8.10
* which OS/distro Ubuntu

### Steps to reproduce
```
> common-env.yaml
sceptre --var-file=common-env.yaml config/stack.yaml 
```
### Expected behaviour
It should validate stack.yaml.

### Actual behaviour
```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sceptre/cli/helpers.py", line 42, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sceptre/cli/__init__.py", line 69, in cli
    "user_variables": setup_vars(var_file, var, merge_vars, debug, no_colour),
  File "/usr/local/lib/python3.8/site-packages/sceptre/cli/helpers.py", line 224, in setup_vars
    return_value.update(parsed)
TypeError: 'NoneType' object is not iterable
```

**Comment by jfalkenstein** [comment]
Huh.... Well that's obviously a bug. But I'm kind of wondering... _why use an empty var-file?_

**Comment by alexharv074** [comment]
I am testing a feature! I can't think of other reasons to pass an empty var file.
