### ISSUE TITLE
A Python Stack Trace Error Occurs if the Template Path does not Exist

### ISSUE THREAD

**Issue by X-Guardian** [Sceptre/sceptre#1314]
### Subject of the issue

If the `path` property of the `template` object contains a reference to a non existent file, Sceptre errors with a full Python stack trace.

### Your environment

* Sceptre, version 4.0.2
* Python 3.9.13

### Expected behaviour

Sceptre should return a managed error with just the `FileNotFound` message like:

```
[2023-03-03 17:09:59] - dev/test - Launching Stack
[2023-03-03 17:09:59] - dev/test - Stack is in the PENDING state
[2023-03-03 17:09:59] - dev/test - Creating Stack
[2023-03-03 17:09:59] - dev/test - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Simon\\Documents\\GitHub\\Sceptre\\sceptre-cdk-handler\\sceptre-example\\example1\\templates\\template.yaml'
```

### Actual behaviour

```
[2023-03-03 17:09:59] - dev/test - Launching Stack
[2023-03-03 17:09:59] - dev/test - Stack is in the PENDING state
[2023-03-03 17:09:59] - dev/test - Creating Stack
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\Scripts\sceptre.exe\__main__.py", line 7, in <module>
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\helpers.py", line 43, in decorated
    return func(*args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\launch.py", line 62, in launch_command
    exit_code = launcher.launch(prune)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\launch.py", line 105, in launch
    code = code or self._deploy(deploy_plan)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\launch.py", line 197, in _deploy
    result = deploy_plan.launch()
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\plan.py", line 170, in launch
    return self._execute(*args)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\plan.py", line 29, in wrapped
    return func(self, *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\plan.py", line 55, in _execute
    return executor.execute(*args)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\executor.py", line 52, in execute
    stack, status = future.result()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\executor.py", line 59, in _execute
    result = getattr(actions, self.command)(*args)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\hooks\__init__.py", line 107, in decorated
    response = func(self, *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\actions.py", line 213, in launch
    status = self.create()
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\hooks\__init__.py", line 107, in decorated
    response = func(self, *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\actions.py", line 91, in create
    create_stack_kwargs.update(self.stack.template.get_boto_call_parameter())
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\template.py", line 224, in get_boto_call_parameter
    return {"TemplateBody": self.body}
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\template.py", line 97, in body
    body = handler.handle()
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\template_handlers\file.py", line 54, in handle
    raise e
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\template_handlers\file.py", line 42, in handle
    with open(path) as template_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Simon\\Documents\\GitHub\\Sceptre\\sceptre-cdk-handler\\sceptre-example\\example1\\templates\\template.yaml'
```

**Comment by zaro0508** [comment]
fixed in PR https://github.com/Sceptre/sceptre-cdk-handler/pull/10
