### ISSUE TITLE
InternalFailure during UpdateStack

### ISSUE THREAD

**Issue by avatarworf** [Sceptre/sceptre#1320]
https://github.com/Sceptre/sceptre/blob/d6c3e9313782df9325ef21041ff31fa1451bde82/sceptre/plan/actions.py#L160-L161

Hello folks, am using v3.3.0 of Sceptre, and running into a max retries failure issue when multiple stacks are being deployed via a `sceptre launch directory/` which contains well over 170 stacks.  Recently this error has been appearing more often, sometimes it's mitigated by a simple re-running.

```
Traceback (most recent call last):
  File ".../python3.7/site-packages/sceptre/plan/actions.py", line 146, in update
    kwargs=update_stack_kwargs,
  File ".../python3.7/site-packages/sceptre/connection_manager.py", line 51, in decorated
    return func(*args, **kwargs)
  File ".../python3.7/site-packages/sceptre/connection_manager.py", line 270, in call
    return getattr(client, command)(**kwargs)
  File ".../python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".../python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the UpdateStack operation (reached max retries: 4): Unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../venv/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File ".../venv/lib64/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".../venv/lib64/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../venv/lib64/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../venv/lib64/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/sceptre/cli/helpers.py", line 43, in decorated
    return func(*args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/sceptre/cli/launch.py", line 62, in launch_command
    exit_code = launcher.launch(prune)
  File ".../venv/lib64/python3.7/site-packages/sceptre/cli/launch.py", line 105, in launch
    code = code or self._deploy(deploy_plan)
  File ".../venv/lib64/python3.7/site-packages/sceptre/cli/launch.py", line 197, in _deploy
    result = deploy_plan.launch()
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/plan.py", line 170, in launch
    return self._execute(*args)
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/plan.py", line 29, in wrapped
    return func(self, *args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/plan.py", line 55, in _execute
    return executor.execute(*args)
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/executor.py", line 52, in execute
    stack, status = future.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/executor.py", line 59, in _execute
    result = getattr(actions, self.command)(*args)
  File ".../venv/lib64/python3.7/site-packages/sceptre/hooks/__init__.py", line 107, in decorated
    response = func(self, *args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/actions.py", line 218, in launch
    status = self.update()
  File ".../venv/lib64/python3.7/site-packages/sceptre/hooks/__init__.py", line 107, in decorated
    response = func(self, *args, **kwargs)
  File ".../venv/lib64/python3.7/site-packages/sceptre/plan/actions.py", line 161, in update
    error_message = exp.response["Error"]["Message"]
KeyError: 'Message'
```

The first issue I believe is that the specific initial error raised InternalFailure doesn't have "Message" response from the ClientError.  Annoying but not critical

Second issue, I'm trying to determine is that the max retries 4, is a boto default.  Is there anyway to increase or alter via sceptre?

**Comment by avatarworf** [comment]
```python
        except botocore.exceptions.ClientError as exp:
            if "Message" in exp.response["Error"]:
                error_message = exp.response["Error"]["Message"]
                if error_message == "No updates are to be performed.":
                    self.logger.info("%s - No updates to perform.", self.stack.name)
                    return StackStatus.COMPLETE
            else:
                raise
```
or do something different for
` exp.response["Error"]["Code"] == "InternalFailure"`

**Comment by zaro0508** [comment]
would you be willing to propose what that `something different` would be in a PR @avatarworf ?

**Comment by zaro0508** [comment]
no response, so closing this issue.
