### ISSUE TITLE
Stack differ raises if a value is None

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1336]
### Subject of the issue
The Stack Differ raises an exception if a parameter value is None.

### Your environment
* version of sceptre - master branch
* version of python (python --version) - 3.10
* which OS/distro - Ubuntu

### Steps to reproduce
Create a config like this:

```yaml
parameters:
  GlueDatabase:
```

Run 
```
sceptre diff -t difflib myapp.yaml
```

### Expected behaviour
This should work.

### Actual behaviour

```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/sceptre/sceptre/cli/helpers.py", line 43, in decorated
    return func(*args, **kwargs)
  File "/app/sceptre/sceptre/cli/diff.py", line 140, in diff_command
    diffs: Dict[Stack, StackDiff] = plan.diff(stack_differ)
  File "/app/sceptre/sceptre/plan/plan.py", line 417, in diff
    return self._execute(*args)
  File "/app/sceptre/sceptre/plan/plan.py", line 29, in wrapped
    return func(self, *args, **kwargs)
  File "/app/sceptre/sceptre/plan/plan.py", line 55, in _execute
    return executor.execute(*args)
  File "/app/sceptre/sceptre/plan/executor.py", line 52, in execute
    stack, status = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/sceptre/sceptre/plan/executor.py", line 59, in _execute
    result = getattr(actions, self.command)(*args)
  File "/app/sceptre/sceptre/hooks/__init__.py", line 95, in decorated
    response = func(self, *args, **kwargs)
  File "/app/sceptre/sceptre/plan/actions.py", line 997, in diff
    return stack_differ.diff(self)
  File "/app/sceptre/sceptre/diffing/stack_differ.py", line 122, in diff
    generated_config = self._create_generated_config(stack_actions.stack)
  File "/app/sceptre/sceptre/diffing/stack_differ.py", line 150, in _create_generated_config
    parameters = self._extract_parameters_from_generated_stack(stack)
  File "/app/sceptre/sceptre/diffing/stack_differ.py", line 172, in _extract_parameters_from_generated_stack
    formatted_parameters[key] = value.rstrip("\n")
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by alexharv074** [comment]
Possible fix:

```diff
diff --git a/sceptre/diffing/stack_differ.py b/sceptre/diffing/stack_differ.py
index eeb942e..fff4dfb 100644
--- a/sceptre/diffing/stack_differ.py
+++ b/sceptre/diffing/stack_differ.py
@@ -169,7 +169,10 @@ class StackDiffer(Generic[DiffType]):
         for key, value in stack.parameters.items():
             if isinstance(value, list):
                 value = ",".join(item.rstrip("\n") for item in value)
-            formatted_parameters[key] = value.rstrip("\n")
+            if value is None:
+                formatted_parameters[key] = None
+            else:
+                formatted_parameters[key] = value.rstrip("\n")
 
         return formatted_parameters
 
```
