### ISSUE TITLE
Ability to show the cloudformation hook status and message in the sceptre output

### ISSUE THREAD

**Issue by sujit-kulkarni** [Sceptre/sceptre#1343]
Cloudformation hook run during the cloudformation stack provisioning is not shown in sceptre output
We use the AWS cloudformation hooks for enforcing the compliance. But either in the Warn mode of Fail mode of the cloudformation hook - the sceptre output doesnot show the hook status, Hook status reason message.

Your environment
Sceptre version -- 4.2.0
python version -- 3.7.19**
which OS/distro -- Linux

Steps to reproduce
Tell us how to reproduce this issue. Please provide sceptre projct files if possible,
you can use https://plnkr.co/edit/ANFHm61Ilt4mQVgF as a base.

Expected behaviour
The sceptre output should show the Aws cloudformation "HookName", "HookStatus" and "HookStatusReason"

Actual behaviour
The sceptre output doesnot show the details of AWS Cloudformation hook.

(venv) [cloudshell-user@ip-10-4-13-6 cfn]$ sceptre create dev/sbucket.yaml
/home/cloudshell-user/venv/lib/python3.7/site-packages/sceptre/stack.py:430: DeprecatedWarning: role_arn is deprecated as of 4.0.0 and will be removed in 5.0.0. It is being renamed to "cloudformation_service_role". You should migrate all uses of "role_arn" to that in order to avoid future breakage.
setattr(self, deprecated_attribute_name, deprecated_value)
Do you want to create 'dev/sbucket.yaml' [y/N]: y
[2023-05-29 05:00:34] - dev/sbucket - Creating Stack
[2023-05-29 05:00:36] - dev/sbucket frp-dev-sbucket AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2023-05-29 05:00:40] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:40] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:40] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Hook invocations complete. Resource creation initiated
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Resource creation Initiated
[2023-05-29 05:01:09] - dev/sbucket Bucket AWS::S3::Bucket CREATE_COMPLETE
[2023-05-29 05:01:09] - dev/sbucket frp-dev-sbucket AWS::CloudFormation::Stack CREATE_COMPLETE
(venv) [cloudshell-user@ip-10-4-13-6 cfn]$ sceptre --version
Sceptre, version 4.2.0
(venv) [cloudshell-user@ip-10-4-13-6 cfn]$ python3 --version
Python 3.7.16
(venv) [cloudshell-user@ip-10-4-13-6 cfn]$

**Comment by zaro0508** [comment]
would you be able to provide a sceptre stack config using a specific hook to reproduce this problem @sujit-kulkarni?

**Comment by sujit-kulkarni** [comment]
Hi @zaro0508 - This is my complete repo structure that uses hook.
![image](https://github.com/Sceptre/sceptre/assets/11851341/22e4f0fe-ba15-4110-aba7-553ff6cee22e)

Individual Configs:
config.yaml
---
project_code: cf-hook-test
region: ap-southeast-2

Env level config -
iam_role: arn:aws:iam::abc:role/role123

user_variables:
  accountid: abc
  environment: d-app-01
  application: cf-hooks

Stack config (Env level)
template_path: templates/sbucket.yaml

role_arn: arn:aws:iam::{{ var.accountid }}:role/roleabc

Let me know if this info helps. If necessary I can connect as well.

Thanks,

**Comment by sujit-kulkarni** [comment]
Hi @zaro0508 , were you able to reproduce his issue?
Let me know if you need any more details from me.

Thanks,
Sujit

**Comment by zaro0508** [comment]
unfortunately what you provided does not help @sujit-kulkarni.  It would help if you can provide the contents of your stack config with the specific sceptre hook you are using (or calling).  Also it might help if you can also provide the cloudformation template file.  Would would probably help the most is if you can provide a very simple set of sceptre project files (sceptre config & cfn templates) that will reproduce the problem you are seeing.

**Comment by sujit-kulkarni** [comment]
Hi @zaro0508 - I have created an **AWS cloudformation hook** (Not Sceptre Hook) for blocking the public access on s3 bucket
Hook Template - 
AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformatopn hook - s3-block-publicaccess publish
Parameters:
  NameWithDashes:
    Type: String
    Default: officeworks-s3bucket-blockpublicaccess
    Description: Name of type seperated by dashes eg My-SuperDuper-Hook
  NameWithColons:
    Type: String
    Description: Name of type seperated by double colons eg My::SuperDuper::Hook
    Default: officeworks::s3bucket::blockpublicaccess
  SchemaHandlerPackage:
    Type: String
    Description: S3 uri for resource type zip eg s3://my-bucket/path/to/my.zip
  AWSHookExecutionRoleArn:
    Type: String
    Description: "IAM role name. Passed to the handler code"
    Default: hook-role
  AWSHookLoggingRoleArn:
    Type: String
    Description: "IAM role name. Passed to the handler code"
    Default: hook-role
Resources:
  Config:
    DependsOn: DefaultVersion
    Type: AWS::CloudFormation::HookTypeConfig
    Properties:
      Configuration: '{"CloudFormationConfiguration":{"HookConfiguration":{"TargetStacks":"ALL","FailureMode":"WARN","Properties":{"TagKeys": "security:confidentiality = public","ValidationStrategy": "resource"}}}}' 
      TypeName: 'officeworks::s3bucket::blockpublicaccess'
  DefaultVersion:
    DependsOn: Version
    Type: AWS::CloudFormation::HookDefaultVersion
    Properties:
      TypeVersionArn: !Ref Version
  Version:
    Type: AWS::CloudFormation::HookVersion
    Properties:
      TypeName: 'officeworks::s3bucket::blockpublicaccess'
      ExecutionRoleArn: !Ref AWSHookExecutionRoleArn
      SchemaHandlerPackage: !Ref SchemaHandlerPackage
      LoggingConfig:
        LogGroupName: !Sub '/aws/cloudformation/hooks/${NameWithDashes}'
        LogRoleArn: !Ref AWSHookLoggingRoleArn


Hook config.xml
---
project_code: frp-global-hooks
region: ap-southeast-2

This is executed as a part of my s3 bucket creation stack. Below is my sample s3 bucket creation template:
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates an Amazon Simple Storage Service (Amazon S3) bucket that you will use to deploy an AWS CloudFormation hook.

Parameters:
  Env:
    Description: Name of the environment.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ofw-hook-deployment
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: ofw-hook-deployment-bucket
        - Key: cfn-hooks:s3-public-access
          Value: false
        - Key: Team
          Value: !Ref 'Env'
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: The name of the bucket you created with this template.
    Value: !Ref 'Bucket'

And the config.xml for the stack -
---
project_code: frp-cf-hook-test
region: ap-southeast-2

Lastly my env level config file -
iam_role: arn:aws:iam::<AccountID>:role/platforms-jenkins

user_variables:
  accountid: <AccountID>
  environment: d-app
  application: cloudformation-hooks
  platforms_contact: ' IT Platforms Team'
  security_contact: 'IT Security Team'
  application_owner: platformteam
  cost_centre: KIT
  security_compliance: none
  security_confidentiality: internal
  automation_uptime: 24x7

Hope this information helps. Look forward to hear from you.

Thanks

**Comment by zaro0508** [comment]
>  I have created an AWS cloudformation hook (Not Sceptre Hook) for blocking the public access on s3 bucket

Ohh, sorry about that I thought you meant Sceptre hook.  

I'm still confused as to the exact problem.   Is the hook failing to deploy/install to AWS using Sceptre?  or does it deploy without error and fails when the hook code executes?

**Comment by sujit-kulkarni** [comment]
Hi @zaro0508 - The hook is able to deploy successfully to AWS using sceptre.
The issue is after the AWS hook is activated, Sceptre doesnot show the HookStatus and HookStatusReason for any of the stack that invokes this hook .
Below you can see that it just says hook invocations complete, there is no information about the hook status or its status reason that we get in the cloudformation describe-stacks output.
**Sceptre**
(venv) [cloudshell-user@ip-10-4-13-6 cfn]$ sceptre create dev/sbucket.yaml
/home/cloudshell-user/venv/lib/python3.7/site-packages/sceptre/stack.py:430: DeprecatedWarning: role_arn is deprecated as of 4.0.0 and will be removed in 5.0.0. It is being renamed to "cloudformation_service_role". You should migrate all uses of "role_arn" to that in order to avoid future breakage.
setattr(self, deprecated_attribute_name, deprecated_value)
Do you want to create 'dev/sbucket.yaml' [y/N]: y
[2023-05-29 05:00:34] - dev/sbucket - Creating Stack
[2023-05-29 05:00:36] - dev/sbucket frp-dev-sbucket AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2023-05-29 05:00:40] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:40] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:40] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
**[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Hook invocations complete. Resource creation initiated**
[2023-05-29 05:00:44] - dev/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Resource creation Initiated
[2023-05-29 05:01:09] - dev/sbucket Bucket AWS::S3::Bucket CREATE_COMPLETE
[2023-05-29 05:01:09] - dev/sbucket frp-dev-sbucket AWS::CloudFormation::Stack CREATE_COMPLETE

**We would like to see Hook-Status and Hook-StatusReason as below, which is shown in cloudformation Describe-stack-events cli.**

**Cloudformatio Describe-stacks**
[cloudshell-user@ip-10-2-87-181 ~]$ aws cloudformation describe-stack-events --stack-name frp-cf-hook-test-sbox-01-sbucket
{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "b21b1fd0-f869-11ed-a5a3-02353bf65130",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "frp-cf-hook-test-sbox-01-sbucket",
            "PhysicalResourceId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2023-05-22T06:27:16.164000+00:00",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "Bucket-CREATE_COMPLETE-2023-05-22T06:27:15.206Z",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "Bucket",
            "PhysicalResourceId": "ofw-hook-deployment",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2023-05-22T06:27:15.206000+00:00",
            "ResourceStatus": "CREATE_COMPLETE",
            "ResourceProperties": "{\"PublicAccessBlockConfiguration\":{\"RestrictPublicBuckets\":\"false\",\"BlockPublicPolicy\":\"false\",\"BlockPublicAcls\":\"false\",\"IgnorePublicAcls\":\"false\"},\"BucketName\":\"ofw-hook-deployment\",\"VersioningConfiguration\":{\"Status\":\"Enabled\"},\"Tags\":[{\"Value\":\"ofw-hook-deployment-bucket\",\"Key\":\"Name\"},{\"Value\":\"false\",\"Key\":\"cfn-hooks:s3-public-access\"},{\"Value\":\"dev\",\"Key\":\"Team\"}]}"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "Bucket-CREATE_IN_PROGRESS-2023-05-22T06:26:53.186Z",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "Bucket",
            "PhysicalResourceId": "ofw-hook-deployment",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2023-05-22T06:26:53.186000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "Resource creation Initiated",
            "ResourceProperties": "{\"PublicAccessBlockConfiguration\":{\"RestrictPublicBuckets\":\"false\",\"BlockPublicPolicy\":\"false\",\"BlockPublicAcls\":\"false\",\"IgnorePublicAcls\":\"false\"},\"BucketName\":\"ofw-hook-deployment\",\"VersioningConfiguration\":{\"Status\":\"Enabled\"},\"Tags\":[{\"Value\":\"ofw-hook-deployment-bucket\",\"Key\":\"Name\"},{\"Value\":\"false\",\"Key\":\"cfn-hooks:s3-public-access\"},{\"Value\":\"dev\",\"Key\":\"Team\"}]}"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "Bucket-1e31fcf9-a11a-4177-a6eb-4f4963b4fd46",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "Bucket",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2023-05-22T06:26:51.654000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "Hook invocations complete.  Resource creation initiated"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "Bucket-533b4f69-0043-4744-8e3b-d3cef220d169",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "Bucket",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2023-05-22T06:26:51.477000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "HookType": "officeworks::s3bucket::blockpublicaccess",
            **"HookStatus": "HOOK_COMPLETE_FAILED",
            "HookStatusReason": "Hook failed with message: **The bucket name ofw-hook-deployment is not excluded from the block public access check.. Failure was ignored under WARN mode.",**
            "HookInvocationPoint": "PRE_PROVISION",
            "HookFailureMode": "WARN"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "Bucket-c83cd88d-dfe0-47c1-b999-b8518db7e3ef",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "Bucket",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2023-05-22T06:26:49.071000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "HookType": "officeworks::s3bucket::blockpublicaccess",
            "HookStatus": "HOOK_IN_PROGRESS",
            "HookStatusReason": "Invoking hook",
            "HookInvocationPoint": "PRE_PROVISION",
            "HookFailureMode": "WARN"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "Bucket-CREATE_IN_PROGRESS-2023-05-22T06:26:48.562Z",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "Bucket",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2023-05-22T06:26:48.562000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceProperties": "{\"PublicAccessBlockConfiguration\":{\"RestrictPublicBuckets\":\"false\",\"BlockPublicPolicy\":\"false\",\"BlockPublicAcls\":\"false\",\"IgnorePublicAcls\":\"false\"},\"BucketName\":\"ofw-hook-deployment\",\"VersioningConfiguration\":{\"Status\":\"Enabled\"},\"Tags\":[{\"Value\":\"ofw-hook-deployment-bucket\",\"Key\":\"Name\"},{\"Value\":\"false\",\"Key\":\"cfn-hooks:s3-public-access\"},{\"Value\":\"dev\",\"Key\":\"Team\"}]}"
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "EventId": "a028b3f0-f869-11ed-a101-02b1603fc56c",
            "StackName": "frp-cf-hook-test-sbox-01-sbucket",
            "LogicalResourceId": "frp-cf-hook-test-sbox-01-sbucket",
            "PhysicalResourceId": "arn:aws:cloudformation:ap-southeast-2:118567634036:stack/frp-cf-hook-test-sbox-01-sbucket/a0204f80-f869-11ed-a101-02b1603fc56c",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2023-05-22T06:26:46.124000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "User Initiated"
        }
    ]
}

Let me know if this gives you complete idea.

Thanks and Regards,
Sujit

**Comment by sujit-kulkarni** [comment]
Sceptre/sceptre
Thank you.
Will you be helping in making this modification in the new release?

Thanks and regards,
Sujit

**Comment by fen9li** [comment]
Hey @zaro0508 
How are you? a quick question about this issue. I have made some changes and have got python3.7,3.8,3.9 unit tests passed. However, I came cross issues with 3.10 & 3.11. Sounds like something wrong when installing pyyaml (5.4.1) on python3.10 & 3.11. Could you please advise if you have any guide on how to set up a standard local developing environment for sceptre? Or maybe you have heard anyone who has solved this issue like the one posted below?

```
py310 installed: alabaster==0.7.13,attrs==23.1.0,Babel==2.12.1,botocore==1.29.116,certifi==2022.12.7,charset-normalizer==3.1.0,click==8.1.3,distlib==0.3.6,docutils==0.16,filelock==3.12.0,idna==3.4,imagesize==1.4.1,iniconfig==2.0.0,Jinja2==3.1.2,jmespath==1.0.1,MarkupSafe==2.1.2,packaging==21.3,parse==1.19.0,platformdirs==3.2.0,pluggy==1.0.0,py==1.11.0,Pygments==2.15.1,pyparsing==3.0.9,python-dateutil==2.8.2,requests==2.28.2,six==1.16.0,snowballstemmer==2.2.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,toml==0.10.2,urllib3==1.26.15,webencodings==0.5.1
py310 run-test-pre: PYTHONHASHSEED='3580329786'
py310 run-test-pre: commands[0] | poetry install --all-extras -v
Using virtualenv: /home/fli/github/sceptre/.tox/py310
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 36 installs, 0 updates, 0 removals, 37 skipped

  • Installing pyyaml (5.4.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/fli/.local/share/pypoetry/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/fli/.local/share/pypoetry/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/fli/.local/share/pypoetry/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
      self.find_sources()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
      mm.run()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
      super().add_defaults()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 201, in get_source_files
    File "/tmp/tmpk_vj139w/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  

  at ~/.local/share/pypoetry/venv/lib64/python3.9/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (5.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==5.4.1)"'.

ERROR: InvocationError for command /home/fli/.local/bin/poetry install --all-extras -v (exited with code 1)
...
_____________________________________________________________________ summary ______________________________________________________________________
  py37: commands succeeded
  py38: commands succeeded
  py39: commands succeeded
ERROR:   py310: commands failed
ERROR:   py311: commands failed
[fli@almalinux sceptre]$ 
```

Thank you.
Feng

**Comment by fen9li** [comment]
> Hey Feng,
> 
> The issue you point out was raised in #1358 and has been resolved as of Sceptre 4.2.2.

Hey Jon,

Thank you for the fix. I will give it a try later this week. Cheers!

Feng

**Comment by fen9li** [comment]
@jfalkenstein , Hey Jon it works. Cheers.

Feng

**Comment by fen9li** [comment]
Hey @zaro0508 

As for the integration test for logging the AWS cloudformation hook, do you mind sheding some lights on the best way to do this? Thank you.

Feng

**Comment by zaro0508** [comment]
We have unit tests to verify the [hook logging method that i mentioned earlier](https://github.com/Sceptre/sceptre/issues/1343#issuecomment-1597364304) @fen9li.   The test is here  https://github.com/Sceptre/sceptre/blob/master/sceptre/plan/actions.py#L832-L855

**Comment by fen9li** [comment]
Hey @zaro0508 Thank you for the quick response. Yes I have updated the [code](https://github.com/Sceptre/sceptre/compare/master...fen9li:sceptre:1343-logging-hook-status) as per your tipped, passed the [pre-commit linting](https://github.com/Sceptre/sceptre/compare/master...fen9li:sceptre:1343-logging-hook-status) and [unit testing](https://github.com/Sceptre/sceptre/compare/master...fen9li:sceptre:1343-logging-hook-status) as required. But I am not very sure about the [integration testing](https://github.com/Sceptre/sceptre/compare/master...fen9li:sceptre:1343-logging-hook-status). 

I have setup my AWS testing account and given it a try run. Some of the integration scenario tests passed, and some other failed, with the reason said 'KeyError ["HookType"]'. I reckon I need to update the integration test code to mock cloudformation hooks, which located in 'integration-tests/features', 'integration-tests/steps' directories etc. Do you have any guideline on how to update the integration testing code please? 

Thank you.

Feng

**Comment by fen9li** [comment]
Hey @jfalkenstein Thank you for the update. Does Sceptre have a roadmap to support CloudFormation hooks?

**Comment by jfalkenstein** [comment]
We discussed them when they first came out, but I don't think a solid case has been made for (1) what use they would have (especially because Sceptre has its own hooks that are rather robust) and (2) what that support would look like. 

If you'd like to propose the feature, that would be a good way to get it considered. I'd be interested about how you're actually using CloudFormation hooks. I've never seen them in use or known anybody who has used them.

**Comment by zaro0508** [comment]
We would appreciate it if you could do a PR to the Sceptre/sceptre repo of your change @fen9li.  Once we have that PR we can provide you more help.

Regarding your question about Sceptre supporting cloudformation hooks..  Since cloudformation hooks are just implemented as lambdas in AWS I don't know (or see) how else Sceptre can support it.   Sceptre already supports the ability to deploy lambdas so once it's deployed you will have your cloudformation hook in place, no?  If you like you can join the [Sceptre slack channel](https://github.com/Sceptre/sceptre/blob/master/README.md#communication) to discuss this with @jfalkenstein.  I'm sure he would love to talk to you.

**Comment by fen9li** [comment]
Hey @zaro0508 Thank you for your response, I have created a [pull request](https://github.com/Sceptre/sceptre/pull/1369) as per your advise. Some of the integration scenario tests passed, and some other failed, with the reason said 'KeyError ["HookType"]'. Could you please take a look on this case when you have some time? Thank you.

**Comment by fen9li** [comment]
Hey @jfalkenstein Thank you for your response. I am looking for some help on integration test. Sounds like some mis understanding. Sorry about this.

**Comment by fen9li** [comment]
Hey @zaro0508 sorry for missing your invitation. I am not very frequently check that email box. It was expired. Do you mind resending me another one? Thank you.

Feng
