### ISSUE TITLE
Unable to install Sceptre >= 4.0 since release of cython 3.0.0

### ISSUE THREAD

**Issue by dmarra** [Sceptre/sceptre#1358]
### Subject of the issue
cython 3.0.0 was released ~1 hour ago. Since then, Sceptre has not been able to build due to its dependency on pyyaml (which is the true source of the problem). 

See https://github.com/yaml/pyyaml/issues/601

### Your environment
* version of sceptre: 4.2.1
* version of python: 3.10
* which OS/distro: ubuntu

### Steps to reproduce
run pip install with the following requirements.txt:

```
sceptre>=4.0
pytest>=3.6
coverage>=4.5
setuptools_scm>=6.2
build
twine>=4.0
```

### Expected behaviour
successful installation of dependencies

### Actual behaviour
I get the following output (NOTE: some sensitive information redacted):

```
Collecting sceptre>=4.0 (from -r requirements.txt (line 1))
  Obtaining dependency information for sceptre>=4.0 from https://files.pythonhosted.org/packages/03/80/26cf35155de1611084a9dfc242ce08bb774548a40729b904c745f1ad0257/sceptre-4.2.1-py3-none-any.whl.metadata
  Downloading sceptre-4.2.1-py3-none-any.whl.metadata (12 kB)
Collecting pytest>=3.6 (from -r requirements.txt (line 2))
  Obtaining dependency information for pytest>=3.6 from https://files.pythonhosted.org/packages/33/b2/741130cbcf2bbfa852ed95a60dc311c9e232c7ed25bac3d9b8880a8df4ae/pytest-7.4.0-py3-none-any.whl.metadata
  Downloading pytest-7.4.0-py3-none-any.whl.metadata (8.0 kB)
Collecting coverage>=4.5 (from -r requirements.txt (line 3))
  Obtaining dependency information for coverage>=4.5 from https://files.pythonhosted.org/packages/b4/bd/1b2331e3a04f4cc9b7b332b1dd0f3a1261dfc4114f8479bebfcc2afee9e8/coverage-7.2.7-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux[20](REDACTED#step:4:21)14_x86_64.whl.metadata
  Downloading coverage-7.2.7-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.7 kB)
Collecting setuptools_scm>=6.2 (from -r requirements.txt (line 4))
  Downloading setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 5.5 MB/s eta 0:00:00
Collecting build (from -r requirements.txt (line 5))
  Downloading build-0.10.0-py3-none-any.whl (17 kB)
Collecting twine>=4.0 (from -r requirements.txt (line 6))
  Downloading twine-4.0.2-py3-none-any.whl (36 kB)
Collecting boto3<2,>=1.3.0 (from sceptre>=4.0->-r requirements.txt (line 1))
  Obtaining dependency information for boto3<2,>=1.3.0 from REDACTED#step:4:22)84813532f743ca607bfb28c/boto3-1.28.3-py3-none-any.whl.metadata
  Downloading boto3-1.28.3-py3-none-any.whl.metadata (6.6 kB)
Collecting cfn-flip<2.0.0,>=1.2.3 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading cfn_flip-1.3.0-py3-none-any.whl (21 kB)
Collecting click<9.0,>=7.0 (from sceptre>=4.0->-r requirements.txt (line 1))
  Obtaining dependency information for click<9.0,>=7.0 from REDACTED#step:4:23)/b3/1da4ea0efa2e5ae410a347be614162ca08bd24a84059938aa5122d1e751b/click-8.1.5-py3-none-any.whl.metadata
  Downloading click-8.1.5-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama<0.4.4,>=0.2.5 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting deepdiff<6.0,>=5.5 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading deepdiff-5.8.1-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.5/69.5 kB 47.4 MB/s eta 0:00:00
Collecting deprecation<3.0,>=2.0 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting jinja2<4.0,>=3.0 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 22.0 MB/s eta 0:00:00
Collecting jsonschema<3.3,>=3.2 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 70.6 MB/s eta 0:00:00
Collecting networkx<2.7,>=2.6 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 22.8 MB/s eta 0:00:00
Collecting packaging<22.0,>=16.8 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 214.4 MB/s eta 0:00:00
Collecting pyyaml<6.0,>=5.1 (from sceptre>=4.0->-r requirements.txt (line 1))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 129.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 20[23]REDACTED#step:4:24)-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line [25](REDACTED)1, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line [33](REDACTED)6, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-ciw2qcta/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line [107](REDACTED), in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
```

**Comment by Vulonus** [comment]
i'm having the same issue while installing `aws-sso-util`. I'll contact the devs...

**Comment by jfalkenstein** [comment]
Ok, so I was able to replicate this issue in Python 3.10.

**Comment by jfalkenstein** [comment]
It looks like, from experimenting with this, that everything installs correctly using PyYaml v6 rather than v5.4.1 we're on right now.

**Comment by jfalkenstein** [comment]
I'm working on a fix for this.

**Comment by jfalkenstein** [comment]
Yeah... my fix is failing in builds and I don't quite know why.

**Comment by dmarra** [comment]
@jfalkenstein I have seen the fix linked below being floated around as a temporary workaround until pyyaml team fixes the core issue:

https://github.com/pi-hole/pi-hole/commit/d20c433a4ad82470b9b68c7a969f8fe09b2219cc

Not sure if this is helpful at all, since it seems to require the end user to install the cython dependency themselves

**Comment by jfalkenstein** [comment]
@dmarra That fix certainly works for _users_ of Sceptre. My company has already implemented that fix. But unfortunately, I don't think we can do that fix _within_ Sceptre to apply to users who install Sceptre. In other words, we can't directly fix PyYaml for our users. 

Upgrading to v6 of PyYaml appears to work and I think we've figured out the fix. Hoping to get that fix out soon.

**Comment by dmarra** [comment]
@jfalkenstein that makes sense. 

Thanks for jumping on this fix. Let me know how I can help if you need it.

**Comment by jfalkenstein** [comment]
According to comments on https://github.com/aws/aws-cli/issues/8036#issuecomment-1638544754, the issue has to do with the build process when there is no pre-compiled wheel for your platform/OS. PyYaml v6 has precompiled wheels for Py3.10 and Py3.11. **Unfortunately, if there is no precompiled wheel for your platform, you will still encounter this issue.**

In our testing, using an Alpine Docker image still encountered this issue.  There's a [comment](https://github.com/aws/aws-cli/issues/8036#issuecomment-1638679410) on that issue that seems to give instructions for Alpine linux (I haven't tested it, though).

As of right now, I'm working on getting out a release of Sceptre for v6.0. This should at least reduce the "blast radius" of this issue until PyYaml releases an update. My fix will be setting PyYaml to `^6.0`, which will automatically pick up whatever fix PyYaml releases (hopefully soon).

**Comment by Vulonus** [comment]
@jfalkenstein I'm using python 3.11 on windows 10, and I managed to install it on a different machine with similar specs and same python version/OS not too long ago. I don't remember the pyyaml version though.

**Comment by pliniodng** [comment]
Hello guys,

The `pyyaml` team just released a fix for this issue via release `6.0.1`: https://github.com/yaml/pyyaml/issues/601#issuecomment-1639515421

They still did not provide a fix for the `5.x` version, which is still used by Sceptre 3.x, but it seems they are working on it.

It would be nice to also hotfix Sceptre `3.x`, as I believe some people (like myself) haven't been able to migrate to Sceptre 4.0 yet. I'm actually blocked from fixing the issue in one of my company's Repo due to Sceptre correctly setting version constrains in `pyyaml` (`"PyYaml>=5.1,<6.0`)

**Comment by jfalkenstein** [comment]
Alright, my PR upgrading to v6.0.1 appears to be working. I hope to get that released laster today.

@pliniodng, regarding a hotfix for v3, I'll need to explore that.

**Comment by pliniodng** [comment]
Thank you @jfalkenstein. 😃

**Comment by jfalkenstein** [comment]
v4.2.2 is Currently releasing as we speak. This will upgrade PyYaml to 6.0.1 which should (under MOST circumstances) solve the immediate problem. 

**This does not fix previous versions of Sceptre.** Until/unless PyYaml releases a hotfix for v5, previous versions of Sceptre will still be broken. I'm working to try to figure out how to issue a hotfix for Sceptre v3 (https://github.com/Sceptre/sceptre/pull/1360), but tests are failing and I don't understand why at the moment. 

Thank you to everyone who helped point this out and cross-link to similar issues!

Until/Unless PyYaml issues a v5 patch or we release a v3 hotfix, the way to resolve this issue can be found in this comment: https://github.com/aws/aws-cli/issues/8036#issuecomment-1638679410. I've tested this out locally and it appears to work.
