### ISSUE TITLE
docker image broken

### ISSUE THREAD

**Issue by jordiprats** [Sceptre/sceptre#1514]
### docker image not workingSubject of the issue

With the latest version of the docker image I'm getting the following trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click-8.1.6-py3.9.egg/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click-8.1.6-py3.9.egg/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click-8.1.6-py3.9.egg/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click-8.1.6-py3.9.egg/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click-8.1.6-py3.9.egg/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click-8.1.6-py3.9.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sceptre/cli/helpers.py", line 42, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sceptre/cli/launch.py", line 50, in launch_command
    launcher.print_operations(prune)
  File "/usr/local/lib/python3.9/site-packages/sceptre/cli/launch.py", line 75, in print_operations
    deploy_plan = self._create_deploy_plan()
  File "/usr/local/lib/python3.9/site-packages/sceptre/cli/launch.py", line 99, in _create_deploy_plan
    plan = self._make_plan(self._context)
  File "/usr/local/lib/python3.9/site-packages/sceptre/plan/plan.py", line 48, in __init__
    self.config_reader = ConfigReader(context)
  File "/usr/local/lib/python3.9/site-packages/sceptre/config/reader.py", line 135, in __init__
    self._add_yaml_constructors(["sceptre.hooks", "sceptre.resolvers"])
  File "/usr/local/lib/python3.9/site-packages/sceptre/config/reader.py", line 192, in _add_yaml_constructors
    node_class = entry_point.load()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'resolver.rcmd'
```

Switching to 3.1.0 works fine, I don't see anything that it is now required here: https://hub.docker.com/r/cloudreach/sceptre I might have missed something somewhere else

### Your environment
* docker images: 3.2.2, 3.2.1

### Steps to reproduce
Run sceptre using docker:

```
docker run -i -e AWS_PROFILE=demo -v $(pwd):/project -v /Users/demo/.aws/:/root/.aws/:ro cloudreach/sceptre:3.2.2 launch ...
docker run -i -e AWS_PROFILE=demo -v $(pwd):/project -v /Users/demo/.aws/:/root/.aws/:ro cloudreach/sceptre:3.1.0 launch ...
```

### Expected behaviour
It should work

### Actual behaviour
It fails

**Comment by zaro0508** [comment]
wrong location official docker images have moved to https://hub.docker.com/r/sceptreorg/sceptre/tags

**Comment by zaro0508** [comment]
we need to update the docs at https://docs.sceptre-project.org/latest/docs/install.html#using-docker-image

**Comment by jprats-godaddy** [comment]
You are missing the "org" but here:

https://github.com/zaro0508/sceptre/commit/5b83d94a6972d882790e3c115d48006695324929#diff-fa8b65f13e35bc5a117f0fcc2ba4f39775674c888e7ee27914c96153c0103751R40
