### ISSUE TITLE
Support for multiple paths / files

### ISSUE THREAD

**Issue by sopeters** [Sceptre/sceptre#617]
I'd like to launch a sceptre run for multiple config directories, e.g.

sceptre launch "development/dir1 development/dir2"

I'm currently getting:

Do you want to launch 'development/dir1 development/dir2' [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/sceptre", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 37, in decorated
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sceptre/cli/launch.py", line 39, in launch_command
    responses = plan.launch()
  File "/usr/lib/python3.6/site-packages/sceptre/plan/plan.py", line 121, in launch
    return self._execute(*args)
  File "/usr/lib/python3.6/site-packages/sceptre/plan/plan.py", line 36, in _execute
    executor = SceptrePlanExecutor(self.command, self.launch_order)
  File "/usr/lib/python3.6/site-packages/sceptre/plan/executor.py", line 35, in __init__
    self.num_threads = len(max(launch_order, key=len))
ValueError: max() arg is an empty sequence

**Comment by mike-rsi** [comment]
What OS are you running Sceptre on?

**Comment by sopeters** [comment]
I run it in a docker container based on alpine and also MacOS

**Comment by ngfgrant** [comment]
Ok, appreciate that would avoid adding another layer in docker although not sure about adding this at the CLI level off the top of my head I can't think of a nice way to do it. 

In dockerfile you could do something like:

`RUN sceptre launch development/dir1  &&  sceptre launch development/dir2`

That might achieve the same thing in a single run command?

**Comment by connec** [comment]
Also, if there's a reason for launching `development/dir2` after `development/dir1` you could add an [explicit dependency](https://sceptre.cloudreach.com/latest/docs/stack_config.html#dependencies):

```
# development/dir2.yaml
...
dependencies:
- dir2
```

**Comment by pwrmiller** [comment]
I've submitted a PR (see above) for the specification of an alternative 'config' path. This allows for multiple configurations in the same project with different paths (this is useful if many projects are using the same templates in the same repository).

**Comment by zaro0508** [comment]
closing since @connec pointed out a way to solve this issue.
