### ISSUE TITLE
2.2.0 breaks on python <3.5

### ISSUE THREAD

**Issue by mitom** [Sceptre/sceptre#808]
I am getting the following on python 2.7 with sceptre 2.2.0:

```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 7, in <module>
    from sceptre.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/sceptre/cli/__init__.py", line 18, in <module>
    from sceptre.cli.new import new_group
  File "/usr/local/lib/python2.7/dist-packages/sceptre/cli/new.py", line 7, in <module>
    from sceptre.config.reader import STACK_GROUP_CONFIG_ATTRIBUTES
  File "/usr/local/lib/python2.7/dist-packages/sceptre/config/reader.py", line 28, in <module>
    from sceptre.stack import Stack
  File "/usr/local/lib/python2.7/dist-packages/sceptre/stack.py", line 11, in <module>
    from typing import Mapping, Sequence
ImportError: No module named typing
```

The typing module was [introduced](https://docs.python.org/3/library/typing.html) in python 3.5

**Comment by ngfgrant** [comment]
Thanks @mitom will look to see if this can be imported in another way

**Comment by ngfgrant** [comment]
I think this is just the case of https://pypi.org/project/typing/ not being imported in requirements. Not sure how the 2.7 build succeeded though. https://github.com/Sceptre/sceptre/pull/809 should fix the issue
