### ISSUE TITLE
Switching to sceptre docker giver PyYAML error for termination protection

### ISSUE THREAD

**Issue by Marakai** [Sceptre/sceptre#862]
Using `cloudreach/sceptre:latest`, I'm migrating my sceptre projects to use the Docker container instead of the "local" installation (or virtenv) and am receiving this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre==2.2.1', 'console_scripts', 'sceptre')()
  File "/usr/local/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/cli/launch.py", line 35, in launch_command
    plan = SceptrePlan(context)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/plan/plan.py", line 34, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/config/reader.py", line 221, in construct_stacks
    stack = self._construct_stack(rel_path, stack_group_config)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/config/reader.py", line 452, in _construct_stack
    config = self.read(rel_path, stack_group_config)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/config/reader.py", line 274, in read
    this_config = self._recursive_read(directory_path, filename, config)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/config/reader.py", line 315, in _recursive_read
    child_config = self._render(directory_path, filename, stack_group_config) or {}
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.2.1-py3.6.egg/sceptre/config/reader.py", line 362, in _render
    config = yaml.safe_load(rendered_template)
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/__init__.py", line 162, in safe_load
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/__init__.py", line 114, in load
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 43, in get_single_data
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 52, in construct_document
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 399, in construct_yaml_seq
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 122, in construct_sequence
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 122, in <listcomp>
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 92, in construct_object
  File "/usr/local/lib/python3.6/site-packages/PyYAML-5.1.2-py3.6-linux-x86_64.egg/yaml/constructor.py", line 420, in construct_undefined
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!stack_termination_protection'
  in "<unicode string>", line 10, column 7:
        - !stack_termination_protection 'e ... 
          ^
```

Google tells me this is a result of using the wrong(deprecated?) loader method in PyYAML.

My config file is nothing special, it merely has:

```
...
hooks:
  after_create:
    - !stack_termination_protection 'enabled'
  after_update:
    - !stack_termination_protection 'enabled'
```

out of paranoia, after some unfortunate stack deletions when creation/update failed.

This bug seems to be known from PyYAML 5.1.1 and was supposedly fixed in PyYAML 5.1.2 but that's what seems to have been used in the Docker image. Am I missing something?

**Comment by ngfgrant** [comment]
This looks like the `stack_termination_protection` resolver is not installed?

**Comment by Marakai** [comment]
Gods, I'm getting old... :( I could not recall ever having separately installed that. Which was true: rather I had also forgotten that I had embedded it into a base package I used across all sceptre stacks because it was so convenient.

Just ignore me...  I shall now hang my head in shame, slink off and proceed to create a custom image.

**Comment by ngfgrant** [comment]
@Marakai no shame here. Glad I could help also glad to hear your making use of the docker image!
