### ISSUE TITLE
list output command fails with TypeError

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#881]
I'm using sceptre v2.3.0.  When i run sceptre to list outputs i get the following error: "TypeError: sequence item 0: expected str instance, dict found"

```
> sceptre launch --yes prod/bug.yaml
[2020-02-14 11:13:05] - prod/bug - Launching Stack
[2020-02-14 11:13:05] - prod/bug - Stack is in the PENDING state
[2020-02-14 11:13:05] - prod/bug - Creating Stack
[2020-02-14 11:13:07] - prod/bug bug AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2020-02-14 11:13:11] - prod/bug S3Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2020-02-14 11:13:11] - prod/bug S3Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Resource creation Initiated
[2020-02-14 11:13:32] - prod/bug S3Bucket AWS::S3::Bucket CREATE_COMPLETE
[2020-02-14 11:13:36] - prod/bug bug AWS::CloudFormation::Stack CREATE_COMPLETE

> sceptre list outputs prod/bug.yaml
Traceback (most recent call last):
  File "/Users/zaro0508/.virtualenvs/py36-default/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/sceptre/cli/list.py", line 92, in list_outputs
    write(responses, context.output_format)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 80, in write
    output = "---\n".join(var)
TypeError: sequence item 0: expected str instance, dict found
```

sceptre bug.yaml template:
``` 
template_path: bug.yaml
stack_name: bug
```

Cloudformation template:
```
Description: test template
AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-S3Bucket'
```

**Comment by ngfgrant** [comment]
Hey @zaro0508 could you try with a virtualenv and sceptre <2.3? Wondering if this is a new thing or always existed

**Comment by zaro0508** [comment]
It looks like a regression.  It works great with v2.2.1

```
> sceptre list outputs prod/bug.yaml
[
    {
        "prod/bug": [
            {
                "OutputKey": "S3Bucket",
                "OutputValue": "bug-s3bucket-syw636illl5e",
                "ExportName": "us-east-1-bug-S3Bucket"
            }
        ]
    }
]
```

**Comment by ngfgrant** [comment]
Thanks - that was my worry. One quick thing to try to help pin the bug down:

With 2.3.0 could you try the same but use `--output json` option?

**Comment by zaro0508** [comment]
that works.  i guess the problem is `text` output?
```
➜  sceptre --version
Sceptre, version 2.3.0
➜  sceptre --output json list outputs prod/bug.yaml
[
    {
        "prod/bug": [
            {
                "OutputKey": "S3Bucket",
                "OutputValue": "bug-s3bucket-2ouo2ewqljer",
                "ExportName": "us-east-1-bug-S3Bucket"
            }
        ]
    }
]
```

**Comment by ngfgrant** [comment]
Yeh looks like the change in https://github.com/Sceptre/sceptre/commit/06131500c4b16730d1b2607d0a15c25728f4b15d will have broken this.

I think probably we could provide a nicer error message. Thoughts?

**Comment by zaro0508** [comment]
not sure i understand @ngfgrant there shouldn't be any errors at all so how would a nicer error message help?

**Comment by ngfgrant** [comment]
I think it’s that the text can represent an object so either we try and fix that if there is an object present and present some text representation. Or we display a message saying that the output contains an u unparsable object ..?

**Comment by zaro0508** [comment]
how about we display something similar to `aws cloudformation list-exports`?

```
➜  aws cloudformation --output json list-exports|grep -i bug  -C1
        {
            "ExportingStackId": "arn:aws:cloudformation:us-east-1:563295687221:stack/bug/0353d330-5037-11ea-8522-0a726edfb5e3",
            "Name": "us-east-1-bug-S3Bucket",
            "Value": "bug-s3bucket-1n3sd7lt25c3u"
        },

➜  aws cloudformation --output text list-exports|grep -i bug
EXPORTS	arn:aws:cloudformation:us-east-1:563295687221:stack/bug/0353d330-5037-11ea-8522-0a726edfb5e3	us-east-1-bug-S3Bucket	bug-s3bucket-2ouo2ewqljer
```

so something like this..
```
OUTPUTS    S3Bucket     bug-s3bucket-2ouo2ewqljer        us-east-1-bug-S3Bucket
```

**Comment by andy-fox-rozettatechnology** [comment]
here's a potential fix:

helpers.py: 80
            output = "---\n".join([str(v) for v in var ])
