### ISSUE TITLE
getting Error: `found unhashable key` when running `sceptre new group MyGroup`

### ISSUE THREAD

**Issue by schlichtanders** [Sceptre/sceptre#882]
just tried to run `sceptre new group MyGroup` on a kind of empty project, and got the error below.

My toplevel ``mysceptreproject/config/config.yaml`` contains the following:
```yaml
project_code: myprojectcode
region: {{ var.region }}
```

Here the error message
```
sceptre new group MyGroup
Do you want initialise config.yaml? [y/N]: y
Traceback (most recent call last):
  File "/Users/myuser/opt/anaconda3/envs/sceptre/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/sceptre/cli/new.py", line 39, in new_stack_group
    _create_new_stack_group(config_dir, stack_group)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/sceptre/cli/new.py", line 109, in _create_new_stack_group
    _create_config_file(config_dir, folder_path)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/sceptre/cli/new.py", line 151, in _create_config_file
    parent_config = _get_nested_config(config_dir, path)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/sceptre/cli/new.py", line 130, in _get_nested_config
    config.update(yaml.safe_load(config_file))
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/constructor.py", line 405, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/myuser/opt/anaconda3/envs/sceptre/lib/python3.7/site-packages/yaml/constructor.py", line 134, in construct_mapping
    "found unhashable key", key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "/Users/myuser/mysceptreproject/config/config.yaml", line 2, column 9
found unhashable key
  in "/Users/myuser/mysceptreproject/config/config.yaml", line 2, column 10
```

my best bet is that jinja templating is not supported currently on the top-level config.yaml, or at least not together with the automatic stackgroup creation. Would be nice to have though.

This was just run now on a fresh sceptre installation on a fresh conda environment with Python 3.7

**Comment by zaro0508** [comment]
maybe you just need to pass in something for var.region?  how about trying `sceptre --var "region=us-east-1" new group MyGroup`?

**Comment by ngfgrant** [comment]
@1oglop1 cant remember, did you work on this?

**Comment by 1oglop1** [comment]
@ngfgrant Sorry I have never worked on this bcs I've never find a use case to write such a long command to create a directory and 1 file.

Howeve I did few tests and I could replicate this with 
Sceptre `v2.2.1` and `v2.3.0` 
Python `3.6.9`

## Expected behaviour
### When `config.yaml` contains strings only
<project_root>/config/config.yaml
```
project_code: prj
region: eu-west-1
```

```
Do you want initialise config.yaml? [y/N]: y
Please enter a region [eu-west-1]: <expects input here>
```

### When `config.yaml` contains Jinja
<project_root>/config/config.yaml
```
project_code: prj
region: {{ var.region }}
```

```
Do you want initialise config.yaml? [y/N]: y
Please enter a region [{{ var.region }}]: <expects input here>
```


## Current behaviour
For strings works as expected.
For Jinja crashes with exception.


### Tested methods:

<project_root>/config/config.yaml
A)
```
project_code: prj
region: {{ var.region }}
```
B)
```
project_code: {{ var.project }}
region: x
```

Sceptre commands
A) `sceptre new group MyGroup`
B) `sceptre --var region='eu-west-1' new group MyGroup`
C) `sceptre --var project='prj' new group MyGroup`

### The results:
This happens when user responds `y` to this questions:
>Do you want initialise config.yaml? [y/N]:

Sceptre then reads the root `config.yaml` (not sure if more configs in case this group is nested)
and parses it with PyYAML directly (without processing it through Jinja).

Which probably tries to treat `{{ y }}` as as nested dict or so. It fails on yaml syntax

### To replicate the error
```python
import yaml

yaml.load('x: {{y}}')
```
#### Results in 
```
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 1, column 4:
    x: {{y}}
       ^
found unhashable key
  in "<unicode string>", line 1, column 5:
    x: {{y}}
```

#### What PyYAML expects to do with `{{ }}`
As I said it tries to parse the yaml where `{}` means empty dict.

```python
yaml.load('x: {}')
# {'x': {}}
yaml.load('x: {y}')
# {'x': {'y': None}}
yaml.load('x: {y: {}}')
# {'x': {'y': {}}}
```

## Workaround (solution)

The workaround is to suggest PyYAML to treat `region: {{ var.region }}` as string 
`region: '{{ var.region }}'`

This produces an expected result as:
```
Do you want initialise config.yaml? [y/N]: y
Please enter a region [{{ var.region }}]: <expects input here>
```



#### Why?
This is not exactly error of PyYAML but YAML itself.

Due the weird nature of YAML I already suggested similar workarounds for variable types:
**Boolean**: `true`=> `True`, `no` => `False` -> `'true'`=> `true`, `'no'`=>`no`
**Numbers starting with 0**: `012` => `12` -> `'012'` => `012`

I suggest to @schlichtanders look up how the yaml works, especially the bad parts to avoid this in future because YAML can be tricky.

## Conclusion

The results of my tests suggest that neither python version or sceptre version or even PyYAML version would make much difference

@ngfgrant 
`--debug` flag does not make a difference (there are no logs)

I

**Comment by schlichtanders** [comment]
Dear @1oglop1 
thank you very much for inspecting this issue and for even finding the root course and the workaround

yes I think the issue can then be solved

**Comment by schlichtanders** [comment]
just a last question.

If I understood it correctly, there are two solutions
1. one would be to write a preprocessor which makes the code to be correct yaml, i.e. adding quotation marks

however this has the disadvantage the jinja templates can of course do anything in principle, so that a preprocessor is actually not a valid approach.

2. An alternative would be to just apply jinja with default parameters (e.g. null everywhere)

But also that may fail, as the jinja may depend on environment variables not available currently or files or other special things...

-------

Can you confirm that this correctly describes the difficulty of fixing this?

**Comment by ngfgrant** [comment]
That sounds about right to me @schlichtanders
