### ISSUE TITLE
ImportError: module 'role' not in sys.modules

### ISSUE THREAD

**Issue by dlahn** [Sceptre/sceptre#933]
I am seeing this intermittently when running Sceptre. Re-running resolves the issue:

```
Traceback (most recent call last):
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/cli/launch.py", line 38, in launch_command
    responses = plan.launch()
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/plan/plan.py", line 130, in launch
    return self._execute(*args)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/plan/plan.py", line 40, in _execute
    return executor.execute(*args)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/plan/executor.py", line 55, in execute
    stack, status = future.result()
  File "/home/david.lahn/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/david.lahn/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/david.lahn/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/plan/executor.py", line 62, in _execute
    result = getattr(actions, self.command)(*args)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/hooks/__init__.py", line 104, in decorated
    response = func(self, *args, **kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/plan/actions.py", line 206, in launch
    status = self.update()
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/hooks/__init__.py", line 104, in decorated
    response = func(self, *args, **kwargs)
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/plan/actions.py", line 128, in update
    self.stack.template.get_boto_call_parameter())
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/template.py", line 320, in get_boto_call_parameter
    return {"TemplateBody": self.body}
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/template.py", line 137, in body
    raise e
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/template.py", line 127, in body
    self._body = self._call_sceptre_handler()
  File "/home/david.lahn/.local/share/virtualenvs/theatre-manager-7cQLIwBJ/lib/python3.8/site-packages/sceptre/template.py", line 172, in _call_sceptre_handler
    module = imp.load_source(self.name, self.path)
  File "/home/david.lahn/.pyenv/versions/3.8.1/lib/python3.8/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 589, in _exec
ImportError: module 'role' not in sys.modules
```

Any ideas?

**Comment by ngfgrant** [comment]
That’s a new one for me...

**Comment by ngfgrant** [comment]
@dlahn out of interest if you ran this in python 3.6 or 3.7 does the problem still exist?
