### ISSUE TITLE
sceptre list resources error

### ISSUE THREAD

**Issue by mundey** [Sceptre/sceptre#951]
python - 3.8.5, also tried on older versions
sceptre list resources test/test.yaml

Traceback (most recent call last):
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/sceptre/cli/list.py", line 47, in list_resources
    write(responses, context.output_format)
  File "/home/jmundey/.local/share/virtualenvs/test-sceptre-_ye-_Sar/lib/python3.8/site-packages/sceptre/cli/helpers.py", line 80, in write
    output = "---\n".join(var)
TypeError: sequence item 0: expected str instance, dict found

sceptre/cli/helpers.py#80
    if output_format == "text":
        if isinstance(var, list):
            output = "---\n".join(var)
        else:
            output = var

**Comment by ngfgrant** [comment]
Python 3.8 isn’t supported yet due to some conflicts and backward compatibility with networkx. Please try with a different version of python. Please can you share your test.yaml?

**Comment by mundey** [comment]
I tried with sceptor docker build available on docker hub. i executed this before or after running create stack.
-ssm.yaml, ssm.yaml is really simple creating ssm param.
---
template_path: ssm.yaml
stack_tagss:
  project:environment: play-ssm
  project:application-group: just-a-test
...

--
/project # python --version
Python 3.6.8
/project # sceptre --version
Sceptre, version 2.4.0
/project # sceptre list resources play/us-east-1/ssm.yaml
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre==2.4.0', 'console_scripts', 'sceptre')()
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.4.0-py3.6.egg/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.4.0-py3.6.egg/sceptre/cli/list.py", line 47, in list_resources
    write(responses, context.output_format)
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.4.0-py3.6.egg/sceptre/cli/helpers.py", line 80, in write
    output = "---\n".join(var)
TypeError: sequence item 0: expected str instance, dict found

**Comment by craighurley** [comment]
@mundey can you try set the output format like either of these examples:

yaml
```
sceptre --output yaml list resources play/us-east-1/ssm.yaml
```

json
```
sceptre --output json list resources play/us-east-1/ssm.yaml
```

The default output is currently `text`, which in this case is not suitable and results in the error: `write
output = "---\n".join(var)`.

Related:
- https://github.com/Sceptre/sceptre/issues/881
- https://github.com/Sceptre/sceptre/pull/832

**Comment by zaro0508** [comment]
python 3.8 not supported yet and output error is already a known issue.
