### ISSUE TITLE
Confusing error message when parsing dependency graph

### ISSUE THREAD

**Issue by dboitnot** [Sceptre/sceptre#976]
If you have malformed YAML in another config file you will get a parser error with no indication which file failed. Example:

```
$ sceptre update -c devl/ecs-appNav.yaml
Traceback (most recent call last):
  File "/Users/dboitnot/.venvs/principia_venv/bin/sceptre", line 8, in <module>
    sys.exit(cli())
...
  File "/Users/dboitnot/.venvs/principia_venv/lib/python3.8/site-packages/sceptre/cli/update.py", line 52, in update_command
    plan = SceptrePlan(context)
  File "/Users/dboitnot/.venvs/principia_venv/lib/python3.8/site-packages/sceptre/plan/plan.py", line 34, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/Users/dboitnot/.venvs/principia_venv/lib/python3.8/site-packages/sceptre/config/reader.py", line 228, in construct_stacks
    stack = self._construct_stack(rel_path, stack_group_config)
...
  File "/Users/dboitnot/.venvs/principia_venv/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 11, column 11:
        - name: tomcat
              ^
```

It took a while before realizing it was talking about a different config file entirely to the one I was launching. /sad_trombone

The error should be trapped and the path of the failing file should be reported.

**Comment by ykhalyavin** [comment]
@dboitnot would you mind to create a pull request with this commit?

**Comment by dboitnot** [comment]
See PR #977
